//
// Created by Danil on 25.08.2024.
//

#ifndef PARSE_BYTECODE_BYTECODE_H
#define PARSE_BYTECODE_BYTECODE_H

#include "types.h"

enum opcode : u1 {
    iload_0 = 0x1a,
    iload_1 = 0x1b,
    iload_2 = 0x1c,
    iload_3 = 0x1d,
    iadd = 0x60,
    imull = 0x68,
    iconst_1 = 0x04,
    iconst_5 = 0x08,
    ireturn = 0xac,
    bipush = 0x10,
    isub = 0x64,
};

enum access_flags : u2 {
    ACC_PUBLIC = 0x0001, //	Declared public; may be accessed from outside its package.
    ACC_PRIVATE = 0x0002, //	Declared private; accessible only within the defining class.
    ACC_PROTECTED = 0x0004, //	Declared protected; may be accessed within subclasses.
    ACC_STATIC = 0x0008, //	Declared static.
    ACC_FINAL = 0x0010, //	Declared final; must not be overridden (§5.4.5).
    ACC_SYNCHRONIZED = 0x0020, //	Declared synchronized; invocation is wrapped by a monitor use.
    ACC_BRIDGE = 0x0040, //	A bridge method, generated by the compiler.
    ACC_VARARGS = 0x0080, //	Declared with variable number of arguments.
    ACC_NATIVE = 0x0100, //	Declared native; implemented in a language other than Java.
    ACC_INTERFACE = 0x0200, //	Declared as an interface.
    ACC_ABSTRACT = 0x0400, //	Declared abstract; no implementation is provided.
    ACC_STRICT = 0x0800, //	Declared strictfp; floating-point mode is FP-strict.
    ACC_SYNTHETIC = 0x1000, //	Declared synthetic; not present in the source code.
    ACC_ANNOTATION = 0x2000, //	Declared as an annotation type.
    ACC_ENUM = 0x4000, //	Declared as an enum type.
    ACC_MANDATED = 0x8000, //	Declared as a mandated class.
};

#endif //PARSE_BYTECODE_BYTECODE_H
